### ISSUE TITLE
テキストが黒、もしくはカスタマイズ可能な色の設定オプションを追加できますか？

### ISSUE THREAD

**Issue by ampcpmgp** [koki-develop/lgtm-generator#84]
素敵なサイトを有難うございます！

一つ要望があります。以下のような、背景が白、もしくは透過でバックグラウンドが白の場合、文字が読みにくくなります。
取り合えず黒に出来るとありがたいと思ったのですが、どうでしょうか。

![LGTM](https://images.lgtmgen.org/36b385fb-bf6e-4c99-a619-dff35ddaeb2e)

![LGTM](https://images.lgtmgen.org/1d2e1b90-af7a-446c-a2c5-e3266750e719)

**Comment by koki-develop** [comment]
@ampcpmgp 
サービスのご利用・ご意見ありがとうございます！！
個人開発でこのように Issue いただいたのが初めてなのでめちゃくちゃ嬉しいです。

こちらの問題は認識はしておりまして、文字の縁取りすることで解決しようかなと思っています。

↓こうだったのが
![before](https://user-images.githubusercontent.com/47014617/166169114-547cea64-0a5c-444c-84b9-dd475f0daab8.jpg)

↓こうなるイメージです
![after](https://user-images.githubusercontent.com/47014617/166169119-ec4e6a30-8e09-4f38-a10b-826c342847bd.jpg)

おっしゃるような仕様も含めいくつか検討したことはあるのですが、以下のような理由から採用していませんでした。

- 案1: ユーザー側で文字色を指定できるようにする
  - 基本的にマウスでポチポチするだけですぐ画像生成できるようにしたいという個人的な方針があるので、色指定の手間をユーザーにかけさせたくない
  - 解決したい問題に対して実装コストが見合っていなさそう
    - 色指定のやり方 ( hex ？ rgb ？カラーピッカー？全部？ ... ) をどうするか等、考えることが多い
- 案2: 画像の明るさを判別して自動で文字色を黒or白にする
  - 白と黒が入り混じっている画像だと結局問題が解決しない

**Comment by koki-develop** [comment]
こちらリリースしました！
また何かあれば Issue ください！

**Comment by ampcpmgp** [comment]
![LGTM](https://images.lgtmgen.org/894cc93b-681a-4720-9d24-d3241c62eaa6)
